name: Build legacy APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Java 17 только для установки SDK (sdkmanager требует 17)
      - name: Setup JDK 17 (for sdkmanager)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: latest
          accept-android-sdk-licenses: true

      - name: Install SDK packages (on Java 17)
        run: |
          yes | sdkmanager --licenses
          yes | sdkmanager \
            "platform-tools" \
            "platforms;android-28" "build-tools;28.0.3" \
            "platforms;android-29" "build-tools;29.0.3" \
            "platforms;android-30" "build-tools;30.0.3"

      # 2) Переключаемся на Java 8 для сборки старого проекта
      - name: Switch to JDK 8 (for Gradle build)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Assemble release APK
        run: ./gradlew clean assembleRelease --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/*.apk
