name: Build debug APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # sdkmanager требует Java 17
      - name: Setup JDK 17 for SDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: latest
          accept-android-sdk-licenses: true

      - name: Install SDK packages
        run: |
          yes | sdkmanager --licenses
          yes | sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # для сборки проекта достаточно 11 (если вдруг упадёт — можно сменить на 8)
      - name: Switch to JDK 11 for build
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Assemble debug APK (already signed with debug keystore)
        run: ./gradlew clean assembleDebug --stacktrace

      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
