name: Build legacy APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Старые проекты часто требуют Java 8
      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: latest
          accept-android-sdk-licenses: true

      # Ставим несколько версий платформ/ билд-тулов — чтобы покрыть старый проект
      - name: Install SDK packages
        run: |
          yes | sdkmanager --licenses
          yes | sdkmanager \
            "platform-tools" \
            "platforms;android-28" "build-tools;28.0.3" \
            "platforms;android-29" "build-tools;29.0.3" \
            "platforms;android-30" "build-tools;30.0.3"

      - name: Make gradlew executable
        run: chmod +x gradlew

      # Для старых проектов AAB может отсутствовать — собираем APK
      - name: Assemble release APK
        run: ./gradlew clean assembleRelease --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/*.apk
